services:
  accounts:
    image: "jayadurga332k/accounts:docker_file"
    container_name: "accounts_ms"
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{"server":{"port":8080}}'
    deploy:
      resources:
        limits:
          memory: 750m
    networks:
      - JustInBank

  cards:
    image: "jayadurga332k/cards:google_jibs"
    container_name: "cards_ms"
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_JSON: '{"server":{"port":8090}}'
    deploy:
      resources:
        limits:
          memory: 750m
    networks:
      - JustInBank

  loans:
    image: "jayadurga332k/loans:build_packs"
    container_name: "loans_ms"
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_JSON: '{"server":{"port":9000}}'
    deploy:
      resources:
        limits:
          memory: 750m
    networks:
      - JustInBank
networks:
  JustInBank:
    driver: "bridge"