build:
  version: "1.0"

accounts:
  message: "Welcome to JustIn Bank accounts related prod APIs "
  contactDetails:
    name: "Ganesha - Product Owner"
    email: "ganesha@justin.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384