build:
  version: "3.0"

accounts:
  message: "Welcome to JustIn Bank accounts related local APIs "
  contactDetails:
    name: "Karthik - Developer"
    email: "karthik@justin.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345