build:
  version: "3.0"

cards:
  message: "Welcome to JustIn Bank cards related local APIs "
  contactDetails:
    name: "Siva - Developer"
    email: "siva@justin.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932