build:
  version: "2.0"

cards:
  message: "Welcome to JustIn Bank cards related QA APIs "
  contactDetails:
    name: "Moksha - QA Lead"
    email: "moksha@justin.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267