build:
  version: "1.0"

loans:
  message: "Welcome to JustIn Bank loans related prod APIs "
  contactDetails:
    name: "Gowtham - Product Owner"
    email: "gowtham@justin.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956