build:
  version: "2.0"

loans:
  message: "Welcome to JustIn Bank loans related QA APIs "
  contactDetails:
    name: "Prahalada - QA Lead"
    email: "prahalada@justin.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467